# Utilisez l'image Ubuntu comme image de base
FROM ubuntu:latest

# Mettez à jour le système et installez Docker
RUN apt-get update && apt-get install -y docker.io

# Installation des dépendances nécessaires
RUN apt-get update && apt-get install -y strongswan && apt-get install -y vim

# Copiez les fichiers de configuration Strongswan
COPY strongswan.conf /etc/strongswan.conf
COPY ipsec.conf /etc/ipsec.conf
COPY ipsec.secrets /etc/ipsec.secrets

# Créez le répertoire /etc/ipsec.d
RUN mkdir -p /etc/ipsec.d

# Générez les clés et les certificats
RUN openssl req -newkey rsa:2048 -nodes -keyout /etc/ipsec.d/server-key.pem -x509 -days 365 -out /etc/ipsec.d/server-cert.pem \
    -subj "/C=CM/ST=State/L=City/O=Organization/CN=example.com" \
    && openssl req -newkey rsa:2048 -nodes -keyout /etc/ipsec.d/client-key.pem -x509 -days 365 -out /etc/ipsec.d/client-cert.pem \
    -subj "/C=CM/ST=State/L=City/O=Organization/CN=example.com"

# Exposez les ports nécessaires pour le VPN
EXPOSE 500/udp
EXPOSE 4500/udp

# Copiez le script de lancement des conteneurs CentOS
#COPY launch_centos2.sh /launch_centos.sh

#RUN chmod +x /launch_centos.sh

# Exécutez le service Strongswan et lancez les conteneurs CentOS au démarrage du conteneur
CMD ["bash", "-c", "ipsec start --nofork "]